### PR TITLE
Embed migrations in binary

### LINKED ISSUE #79: Embed migrations in neurobot binary
The path to the migrations directory is currently [computed at compile time](https://github.com/Automattic/neurobot/blob/ad7525f83ab8b90304363319b328d12fe504cf4b/infrastructure/database/database.go#L24). Instead we should embed migrations in the neurobot binary.

### PR DESCRIPTION
**Pull request by psrpinto**
Migrations are now embedded in the binary at compile time, so no longer need to be present in the target machine at runtime.

Fixes #79

### CODE REVIEW

**Review by ashfame — APPROVED** [review]
Cool! Lets go 🚀

**Comment by ashfame** [comment]
@psrpinto I deployed this to production, but still didn't work. Getting this error: `initializing db migration failed open /home/neurobot/neurobot/migration/.: no such file or directory`

**Comment by psrpinto** [comment]
Mmm, that's weird. It feels like maybe that was not the latest version of the code, since the directory is now called `migrations/` (with a trailing `s`). Let's look at it together.

**Comment by ashfame** [comment]
More than that, what gave away was that it was looking for files at all. We have embedded it now :)

**Pull request merged**
