### PR TITLE
Improve logging

### LINKED ISSUE #1: Implement proper logging
Every log entry should have some context attached to it and must writes its event stream, unbuffered, to `stdout` as per [The12FactorApp](https://12factor.net/logs)

### PR DESCRIPTION
**Pull request by psrpinto**
Fixes  #1

Not being sure whether logs end up in journald is making it harder to debug issues in production. So I went ahead add started using a logging library.  

https://github.com/Sirupsen/logrus seems to be the most widely used Go logging library, but is in maintenance mode.
https://github.com/apex/log is one of the alternatives recommended by Logrus maintainers, and has a similar API to Logrus. So I opted for the latter.

This is just a first step, we can continue to improve logging iteratively.

Current output:

```
2022/04/08 01:09:13  info Loaded environment variables from .env path=./.env
2022/04/08 01:09:13  info Enabling debug? true
2022/04/08 01:09:13  info Using database file: ./neurobot.db
2022/04/08 01:09:33  info Discovered client API     duration=10005 serverName=localhost:8008 serverURL=http://localhost:8008
2022/04/08 01:09:33  info Starting up engine
2022/04/08 01:09:33  info Loading data
2022/04/08 01:09:33  info Adding Log to stdout to workflow #1
2022/04/08 01:09:33  info Adding post message to Matrix room to workflow #2
2022/04/08 01:09:33  info Adding post message to Matrix room 2 to workflow #2
2022/04/08 01:09:33  info Finished starting up engine.
2022/04/08 01:09:33  info Starting up Matrix client(s)
2022/04/08 01:09:33  info Finished waking up all Matrix bots
2022/04/08 01:09:34  info Logged in to homeserver   duration=252 serverName=localhost:8008 username=admin
2022/04/08 01:09:34  info Finished starting primary bot
2022/04/08 01:09:34  info Engine's matrix start up finished
2022/04/08 01:09:34  info Starting webhook listener port=8080
```

### CODE REVIEW

**Comment by ashfame** [comment]
Thanks for working on this! It does make the logging code a lot cleaner.

I have few thoughts around this:

- I think primary purpose of using a logger library is to be able to choose where should the logs go to, without touching the application itself. Right now, we have tied up apex/log as direct dependency in our sub-packages wherever it is used. I think we should be passing the logger instance via factory methods. Doesn't have to be in this PR but this would give us the ability to choose the log handler in `main.go` and allow us to write tests which check whether certain statements were logged. What do you think?
- Using colored cli output on stdout by default would be nice

**Review by ashfame — APPROVED** [review]

**Comment by psrpinto** [comment]
Great points! Replies follow.

> Not all log calls are currently replaced - is that intentional or just a work in progress?

It was intentional indeed, wanted to have some feedback on the approach before investing more time into doing it everywhere.

> I think we should be passing the logger instance via factory methods.

I'm not sure I follow completely but if I understand correctly, you mean we should be injecting the logger instead of doing `logger := log.Log`. apex/log uses a singleton internally, so the call to `log.Log` returns the instance. There will always only be a single instance. So if we would inject it, it would still be the same instance everywhere. Since it's easier to do `logger := log.Log` than injecting (and the result is the same), I opted for not injecting. AFAICT, the library was designed to be used in this way.

> I think primary purpose of using a logger library is to be able to choose where should the logs go to, without touching the application itself.

Indeed, this is essential, agreed. apex/logs supports this (see [examples](https://github.com/apex/log/tree/master/_examples):

```
log.SetHandler(json.New(os.Stderr))
```

This also allows for having different handlers in tests, in production, and in development, if needed.

> Using colored cli output on stdout by default would be nice

**Comment by ashfame** [comment]
> I'm not sure I follow completely but if I understand correctly, you mean we should be injecting the logger instead of doing logger := log.Log. apex/log uses a singleton internally, so the call to log.Log returns the instance. There will always only be a single instance. So if we would inject it, it would still be the same instance everywhere. Since it's easier to do logger := log.Log than injecting (and the result is the same), I opted for not injecting. AFAICT, the library was designed to be used in this way.

Yeah, I saw that it supports singleton pattern, but I was speaking along the lines of controlling what the dependency is as a logger and injecting it. Imagine if we decide to send all our logs to a 3rd party service, right now, that would require changing logger at several places. But if we are doing that in main and then injecting that logger instance, everywhere, does the job. Also, in tests, we can inject a logger to check for certain values whether they were logged, when desired.

I guess, using singleton cover this, since setting a handler on main would affect every usage in sub package. I guess, in tests as well we can set the handler before doing anything? So, do you think singleton in this case provides the same mileage as dependency injection?

Re: colored output, that's just a built in handler that it offers, so we can switch to that in main itself, I think.

**Comment by psrpinto** [comment]
> I guess, in tests as well we can set the handler before doing anything?

Correct, we also can create our own handler specifically for usage in tests, if we need to.

> So, do you think singleton in this case provides the same mileage as dependency injection?

Since that's how the library works internally, and that it makes logging easier (don't need to inject logger in all places), I think it makes sense to embrace it.

**Pull request merged**
